#!/bin/bash

# This file is a part of LoopScalla, a framework for loop calculations
# Loopscalla is covered by the GNU General Public License 3.
# Copyright (C) 2019-2025 Vladyslav Shtabovenko

# Examples:
# /ShellScripts/lsclCount.sh MyProject MyProject MyModel 3 1 --what Tablebase
# ./ShellScripts/lsclCount.sh MyHiggsProject HToGlGl SM 1 --what Tablebase --kira --showmissing
# Stop if any of the commands fails
set -e

export LSCL_SCRIPT_NAME="lsclCount"

if [[ $# -lt 4 ]] ; then    
    echo "${LSCL_SCRIPT_NAME}: You must specify the project, the process name, the model, and the number of the loops!"
    echo "${LSCL_SCRIPT_NAME}: Current command line arguments: ${@}"
fi


lsclScriptDir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"
lsclRepoDir="$(dirname $lsclScriptDir)"

#if [ -z "${lsclEnvSourced}" ]; then
#  . "$lsclRepoDir"/environment.sh
#fi

lsclProjectName="$1"
lsclProcessName="$2"
lsclModelName="$3"
lsclNLoops="$4"

lsclInput=()
lsclOutput=()

lsclInputCount=0
lsclOutputCount=0
showMissingArg=""

if [[ -z "${LSCL_FLAG_KIRA+x}" ]]; then
  export LSCL_FLAG_KIRA=0
fi

if [[ -z "${LSCL_FLAG_SHOW_MISSING+x}" ]]; then
  export LSCL_FLAG_SHOW_MISSING=0
fi

while [[ ${#} -gt 0 ]]; do
  case ${1} in
    --what)
      lsclShowWhat=${2}
      shift
      shift
      ;;
    --kira)
      export LSCL_FLAG_KIRA=1
      echo "${LSCL_SCRIPT_NAME}: Using reduction tables generated by KIRA."      
      shift
      ;;
    --showmissing)
      export LSCL_FLAG_SHOW_MISSING=1   
      shift
      ;;  
    #Basic input parameters
    *)
      lsclBasicArguments+=("$1")
      shift;
      ;;
  esac
done


countMissingFiles () {
  echo
  echo "${LSCL_SCRIPT_NAME}: Original number of input files: ${lsclInputCount}"
  echo "${LSCL_SCRIPT_NAME}: Number of processed files: ${lsclOutputCount}"
  echo "${LSCL_SCRIPT_NAME}: Number of unprocessed files: $((lsclInputCount-lsclOutputCount))"
  if [[ $((lsclInputCount-lsclOutputCount)) -ne 0 ]] ; then
  echo "${LSCL_SCRIPT_NAME}: WARNING! Some files were not processed properly, please check them more carefully!"
  fi
}

showMissingFiles () {
  echo "${LSCL_SCRIPT_NAME}: List of unprocessed files ($((lsclInputCount-lsclOutputCount)) in total):"
  for i in "${lsclInput[@]}"; do      
    lsclFileDirName=$(dirname ${i})  
    lsclFileName=$(basename ${lsclFileDirName})  
    if [ ! -f ${lsclFileDirName}/"$1" ]; then
        echo "${lsclFileName}"
    fi   
  done;
}

showMissingFiles2 () {
  echo "${LSCL_SCRIPT_NAME}: List of unprocessed files ($((lsclInputCount-lsclOutputCount)) in total):"
  for i in "${lsclInput[@]}"; do      
    lsclFileDirName=$(dirname ${i})  
    lsclFileName=$(basename ${lsclFileDirName})  
    if [ ! -f ${lsclFileDirName}/${lsclFileDirName}"$1" ]; then
        echo "${lsclFileName}"
    fi   
  done;
}

case ${lsclShowWhat} in
  
  InputDiagrams)
    lsclInputCount=$(grep -o '#\[ d' $lsclRepoDir/Projects/$lsclProjectName/QGRAF/Output/Files/$lsclProcessName.$lsclModelName.$lsclNLoops.amps | wc -l)
    lsclOutputCount=$(find $lsclRepoDir/Projects/$lsclProjectName/Diagrams/$lsclProcessName/$lsclModelName/$lsclNLoops/Input -type f -name "dia*L$lsclNLoops.frm" | wc -l)
    showMissingVer=-1
    ;;

  Stage0)    
    lsclInputCount=$(find $lsclRepoDir/Projects/$lsclProjectName/Diagrams/$lsclProcessName/$lsclModelName/$lsclNLoops/Input -type f -name "dia*L$lsclNLoops.frm" | wc -l)
    lsclOutputCount=$(find $lsclRepoDir/Projects/$lsclProjectName/Diagrams/$lsclProcessName/$lsclModelName/$lsclNLoops/Stage0 -type f -name "stage0_dia*L$lsclNLoops.res" | wc -l)
    readarray -d '' lsclInput < <(find $lsclRepoDir/Projects/$lsclProjectName/Diagrams/$lsclProcessName/$lsclModelName/$lsclNLoops/Input -type f -name "dia*L$lsclNLoops.frm" -print0);
    showMissingVer=-1    
    ;;

  Stage1)    
    lsclInputCount=$(find $lsclRepoDir/Projects/$lsclProjectName/Diagrams/$lsclProcessName/$lsclModelName/$lsclNLoops/Input -type f -name "dia*L$lsclNLoops.frm" | wc -l)
    lsclOutputCount=$(find $lsclRepoDir/Projects/$lsclProjectName/Diagrams/$lsclProcessName/$lsclModelName/$lsclNLoops/Stage1 -type f -name "stage1_dia*L$lsclNLoops.res" | wc -l)
    readarray -d '' lsclInput < <(find $lsclRepoDir/Projects/$lsclProjectName/Diagrams/$lsclProcessName/$lsclModelName/$lsclNLoops/Input -type f -name "dia*L$lsclNLoops.frm" -print0);
    showMissingVer=-1    
    ;;

  Stage2)    
    lsclInputCount=$(find $lsclRepoDir/Projects/$lsclProjectName/Diagrams/$lsclProcessName/$lsclModelName/$lsclNLoops/Input -type f -name "dia*L$lsclNLoops.frm" | wc -l)
    lsclOutputCount=$(find $lsclRepoDir/Projects/$lsclProjectName/Diagrams/$lsclProcessName/$lsclModelName/$lsclNLoops/Stage2 -type f -name "stage2_dia*L$lsclNLoops.res" | wc -l)
    readarray -d '' lsclInput < <(find $lsclRepoDir/Projects/$lsclProjectName/Diagrams/$lsclProcessName/$lsclModelName/$lsclNLoops/Input -type f -name "dia*L$lsclNLoops.frm" -print0);
    showMissingVer=-1    
    ;;

  
  ExtractedTopologies)
    lsclInputCount=$(find $lsclRepoDir/Projects/$lsclProjectName/Diagrams/$lsclProcessName/$lsclModelName/$lsclNLoops/Input -type f -name "dia*L$lsclNLoops.frm" | wc -l)
    lsclOutputCount=$(find $lsclRepoDir/Projects/$lsclProjectName/Diagrams/$lsclProcessName/$lsclModelName/$lsclNLoops/ExtractedTopologies -type f -name "topos_dia*L$lsclNLoops.m" | wc -l)    
    showMissingVer=-1    
    ;;

  ExtractedLoopIntegrals)
    lsclInputCount=$(find $lsclRepoDir/Projects/$lsclProjectName/Diagrams/$lsclProcessName/$lsclModelName/$lsclNLoops/Input -type f -name "dia*L$lsclNLoops.frm" | wc -l)
    lsclOutputCount=$(find $lsclRepoDir/Projects/$lsclProjectName/Diagrams/$lsclProcessName/$lsclModelName/$lsclNLoops/LoopIntegrals/Form -type f -name "dia*L$lsclNLoops.res" | wc -l)
    showMissingVer=-1    
    ;;    

  CompletedReductions)    
    if [[ ${LSCL_FLAG_KIRA} -ne 1 ]] ; then
      lsclInputCount=$(find $lsclRepoDir/Projects/$lsclProjectName/Diagrams/$lsclProcessName/$lsclModelName/$lsclNLoops/Reductions/*/ -type f -name "LoopIntegrals.m" | wc -l)
      lsclOutputCount=$(find $lsclRepoDir/Projects/$lsclProjectName/Diagrams/$lsclProcessName/$lsclModelName/$lsclNLoops/Reductions/*/ -type f -name "*.tables" | wc -l)
      readarray -d '' lsclInput < <(find $lsclRepoDir/Projects/$lsclProjectName/Diagrams/$lsclProcessName/$lsclModelName/$lsclNLoops/Reductions/*/ -type f -name "LoopIntegrals.m" -print0);
      showMissingVer=2
      showMissingArg="/tablebaseFire.tbl"
    else      
      lsclInputCount=$(find $lsclRepoDir/Projects/$lsclProjectName/Diagrams/$lsclProcessName/$lsclModelName/$lsclNLoops/Reductions/*/ -type f -name "KiraLoopIntegrals" | wc -l)
      lsclOutputCount=$(find $lsclRepoDir/Projects/$lsclProjectName/Diagrams/$lsclProcessName/$lsclModelName/$lsclNLoops/Reductions/*/ -type f -name "kira_KiraLoopIntegrals.m" | wc -l)
      readarray -d '' lsclInput < <(find $lsclRepoDir/Projects/$lsclProjectName/Diagrams/$lsclProcessName/$lsclModelName/$lsclNLoops/Reductions/*/ -type f -name "kira_KiraLoopIntegrals.m" -print0);
      showMissingVer=2
      showMissingArg="/tablebaseKira.tbl"
    fi

    ;;

  TableBases)    
    if [[ ${LSCL_FLAG_KIRA} -ne 1 ]] ; then
      lsclInputCount=$(find $lsclRepoDir/Projects/$lsclProjectName/Diagrams/$lsclProcessName/$lsclModelName/$lsclNLoops/Reductions/*/ -type f -name "*.tables" | wc -l)
      lsclOutputCount=$(find $lsclRepoDir/Projects/$lsclProjectName/Diagrams/$lsclProcessName/$lsclModelName/$lsclNLoops/Reductions/*/ -type f -name "tablebaseFire.tbl" | wc -l)
      readarray -d '' lsclInput < <(find $lsclRepoDir/Projects/$lsclProjectName/Diagrams/$lsclProcessName/$lsclModelName/$lsclNLoops/Reductions/*/ -type f -name "*.tables" -print0);
      showMissingVer=1
      showMissingArg="/tablebaseFire.tbl"

    else
      lsclInputCount=$(find $lsclRepoDir/Projects/$lsclProjectName/Diagrams/$lsclProcessName/$lsclModelName/$lsclNLoops/Reductions/*/ -type f -name "kira_KiraLoopIntegrals.m" | wc -l)
      lsclOutputCount=$(find $lsclRepoDir/Projects/$lsclProjectName/Diagrams/$lsclProcessName/$lsclModelName/$lsclNLoops/Reductions/*/ -type f -name "tablebaseKira.tbl" | wc -l)
      readarray -d '' lsclInput < <(find $lsclRepoDir/Projects/$lsclProjectName/Diagrams/$lsclProcessName/$lsclModelName/$lsclNLoops/Reductions/*/ -type f -name "kira_KiraLoopIntegrals.m" -print0);
      showMissingVer=1
      showMissingArg="/tablebaseKira.tbl"
    fi

    ;;
    
  FillStatements)
    if [[ ${LSCL_FLAG_KIRA} -ne 1 ]] ; then
      lsclInputCount=$(find $lsclRepoDir/Projects/$lsclProjectName/Diagrams/$lsclProcessName/$lsclModelName/$lsclNLoops/Reductions/*/ -type f -name "*.tables" | wc -l)
      lsclOutputCount=$(find $lsclRepoDir/Projects/$lsclProjectName/Diagrams/$lsclProcessName/$lsclModelName/$lsclNLoops/Reductions/*/ -type f -name "fillStatementsFire.frm" | wc -l)
      readarray -d '' lsclInput < <(find $lsclRepoDir/Projects/$lsclProjectName/Diagrams/$lsclProcessName/$lsclModelName/$lsclNLoops/Reductions/*/ -type f -name "*.tables" -print0);
      showMissingVer=1
      showMissingArg="/fillStatementsFire.frm"
    else
      lsclInputCount=$(find $lsclRepoDir/Projects/$lsclProjectName/Diagrams/$lsclProcessName/$lsclModelName/$lsclNLoops/Reductions/*/ -type f -name "kira_KiraLoopIntegrals.m" | wc -l)
      lsclOutputCount=$(find $lsclRepoDir/Projects/$lsclProjectName/Diagrams/$lsclProcessName/$lsclModelName/$lsclNLoops/Reductions/*/ -type f -name "fillStatementsKira.frm" | wc -l)
      readarray -d '' lsclInput < <(find $lsclRepoDir/Projects/$lsclProjectName/Diagrams/$lsclProcessName/$lsclModelName/$lsclNLoops/Reductions/*/ -type f -name "kira_KiraLoopIntegrals.m" -print0);
      showMissingVer=1
      showMissingArg="/fillStatementsKira.frm"
    fi    
    ;;

  ImportedReductionTables)
    if [[ ${LSCL_FLAG_KIRA} -ne 1 ]] ; then
      lsclInputCount=$(find $lsclRepoDir/Projects/$lsclProjectName/Diagrams/$lsclProcessName/$lsclModelName/$lsclNLoops/Reductions/*/ -type f -name "*.tables" | wc -l)
      lsclOutputCount=$(find $lsclRepoDir/Projects/$lsclProjectName/Diagrams/$lsclProcessName/$lsclModelName/$lsclNLoops/Reductions/*/ -type f -name "FireReductionRules.m" | wc -l)
      readarray -d '' lsclInput < <(find $lsclRepoDir/Projects/$lsclProjectName/Diagrams/$lsclProcessName/$lsclModelName/$lsclNLoops/Reductions/*/ -type f -name "*.tables" -print0);
      showMissingVer=1
      showMissingArg="/FireReductionRules.m"
    else
      lsclInputCount=$(find $lsclRepoDir/Projects/$lsclProjectName/Diagrams/$lsclProcessName/$lsclModelName/$lsclNLoops/Reductions/*/ -type f -name "kira_KiraLoopIntegrals.m" | wc -l)
      lsclOutputCount=$(find $lsclRepoDir/Projects/$lsclProjectName/Diagrams/$lsclProcessName/$lsclModelName/$lsclNLoops/Reductions/*/ -type f -name "KiraReductionRules.m" | wc -l)
      readarray -d '' lsclInput < <(find $lsclRepoDir/Projects/$lsclProjectName/Diagrams/$lsclProcessName/$lsclModelName/$lsclNLoops/Reductions/*/ -type f -name "kira_KiraLoopIntegrals.m" -print0);
      showMissingVer=1
      showMissingArg="/KiraReductionRules.m"
    fi    
    ;; 
   

  

  *)
    echo "${LSCL_SCRIPT_NAME}: Error: Unknown mode!"
    exit 1;
    ;;
esac

if [[ ${LSCL_FLAG_SHOW_MISSING} -ne 1 ]] ; then
  countMissingFiles
else 
  if [[ $((lsclInputCount-lsclOutputCount)) -ne 0 ]] ; then
    case ${showMissingVer} in
      -1)
      echo "${LSCL_SCRIPT_NAME}: Error: --showmissing option is not available for this mode."
      ;;
      1)
      showMissingFiles $showMissingArg
      ;;
      2)
      showMissingFiles2 $showMissingArg
      ;;
      *)
      echo "${LSCL_SCRIPT_NAME}: Error: Unknown version of showMissingFiles"
      exit 1;
    esac
  else 
    echo "${LSCL_SCRIPT_NAME}: There are no unprocessed files."
  fi      
fi
